# DEFINITION OF PRICE LEVELS (DISCRETIZATION CAN BE MODIFIED WITH THE STEP SIZE)
PRICE_MIN = 1
PRICE_MAX = 2
PRICE_STEP_SIZE = 1

# DEFINITION OF ENERGY LEVELS (DISCRETIZATION CAN BE MODIFIED WITH THE STEP SIZE)
ENERGY_MIN = 1
ENERGY_MAX = 3
ENERGY_STEP_SIZE = 1

# TRANSITION PROBABILITIES BETWEEN THE DIFFERENT PRICES (FOR EACH PRICE A TRANSITION PROBABILITY MUST BE SPECIFIED)
TRANS_PROB = [[0.3, 0.7], [0.7, 0.3]]

# MAXIMUM TIME STEPS (MUST BE A NATURAL NUMBER GREATER THEN 0)
MAX_TIME = 3

# Initialize state
# Definition of states: [Price, Energy-Level]
INITIAL_STATE = [1, 0]

